[project]
name = "python-starter-kit"
version = "0.1.0"
description = "Python Starter Kit with Claude Code Action"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    # --- 코드 품질 ---
    "bandit>=1.9.4",
    "ruff>=0.15.4", # 린터 & 포매터
]
